#!/bin/bash

echo "For simple: "

for i in a b c d e f g h i
do
echo "letra: $i"
done

N= "Iñigo Sten Asier Pello Roberto"
echo "For simple array:"

echo "Participantes en la 4party: "

for i in ${Nombres}
do
echo "${i}"
done


for i in 'cat direcciones.txt'
do
echo  "${i}"
done

for i in *.sh
do
ls -lh ${i}
done

for((cont= 0 ; ${cont} < 10 ; cont='expr $cont + 1'
do
echo "Ahora valgo > ${cont}"
done


